### PR TITLE
Graphql support

### PR DESCRIPTION
**Pull request by Jylth**
Hi, thanks for the work on this very useful library.

This pull request adds some information on how to easily use this library on a Graphql setup.

Had to change some bits in the interceptor class to make it easier to extend into.

### CODE REVIEW

**Comment by ozkanonur** [comment]
First of all thanks for coming with this idea. However, I couldn't make it work by just doing simple usage. Can you share an example repo that works with this forked version? I couldn't receive requests and responses on rate-limiter side.  If you show me how you do that point then I can make some optimizations there.

**Comment by ozkanonur** [comment]
@Jylth  First of all thanks for coming with this idea. However, I couldn't make it work by just doing simple usage. Can you share an example repo that works with this forked version? I couldn't receive requests and responses on rate-limiter side. If you show me how you do that point then I can make some optimizations there.

**Comment by Jylth** [comment]
Hello @ozkanonur, pleasure to help.

What do you mean exactly by simple usage? 
I tested the following use cases and i didn't notice any issues with them:

GraphQL Query using a custom extended `RateLimiterInterceptor` like explained in the modified section of the README

- Using express
- Using fastify
- As a class and method level interceptor through UseInterceptors
- As a global interceptor through APP_INTERCEPTOR provider
- With RateLimiter decorator

I also tested traditional controller endpoints with the initial `RateLimiterInterceptor` in the same use cases as above to see if i didn't break anything but those were also working correctly.

Also if you don't mind, i will add some unit tests for the behaviors listed above in a different pull request.

**Comment by ozkanonur** [comment]
> Hello @ozkanonur, pleasure to help.
> 
> What do you mean exactly by simple usage?
> I tested the following use cases and i didn't notice any issues with them:
> 
> GraphQL Query using a custom extended `RateLimiterInterceptor` like explained in the modified section of the README
> 
> * Using express
> * Using fastify
> * As a class and method level interceptor through UseInterceptors
> * As a global interceptor through APP_INTERCEPTOR provider
> * With RateLimiter decorator
> 
> I also tested traditional controller endpoints with the initial `RateLimiterInterceptor` in the same use cases as above to see if i didn't break anything but those were also working correctly.
> 
> Also if you don't mind, i will add some unit tests for the behaviors listed above in a different pull request.

It just doesn't work whenever I try. Response is always coming as undefined. I created another branch and then added Graphql (currently only for express based ones) support. There is also a TODO list at end of the documentation, if you want you can help me about them, I am pretty busy with a lot of repositories these days so I am pretty slow to react issues or features on this repository I am sorry about that. And thanks again to make me remember about Graphql support !

**Comment by Jylth** [comment]
To support fastify you will need to pass the context option to the apollo server configuration passing down the correct request/reply object. Like below. So for this lib there is not much you could do about it, just write it in the docs.

example below:

```ts
GraphQLModule.forRoot({
  context: ({ request, reply }) => {
    // assigning request to reply.res will make it work with your current implementation.
    reply.req = request
    return { req: request, res: reply }
   }
})

```

**Comment by ozkanonur** [comment]
> To support fastify you will need to pass the context option to the apollo server configuration passing down the correct request/reply object. Like below. So for this lib there is not much you could do about it, just write it in the docs.
> 
> example below:
> 
> ```ts
> GraphQLModule.forRoot({
>   context: ({ request, reply }) => {
>     // assigning request to reply.res will make it work with your current implementation.
>     reply.req = request
>     return { req: request, res: reply }
>    }
> })
> ```

I am glad that you explain that. Now with version 2.3.0 this library also supports Fastify based Graphql server.

**Pull request closed without merging**
