### PR TITLE
can dynamic rate limit key

### PR DESCRIPTION
**Pull request by tongzcomradez**

### CODE REVIEW

**Comment by ozkanonur** [comment]
Thank you for the PR. Can you add this new field to the documentation? @tongzcomradez

**Comment by tongzcomradez** [comment]
sure @ozkanonur

**Comment by ozkanonur** [comment]
so what is this pr for ? what does generated key exactly do ? keys are already dynamic for per client because it comes from IP address. If you make it dynamic for also single client you can not apply rate limiter to that client.

**Comment by tongzcomradez** [comment]
some api i must use rate limit with user id

**Comment by ozkanonur** [comment]
I will check it out

**Comment by somehowchris** [comment]
So I just need to run some stuff based on a user token.

Basically the need is. You can have multiple machines with multiple IP's but use the same account. In that case you should be able to rate limit on a unique key like a username inside a oauth2 token. Interceptors are run after guards so no real need to do something fancy but just point to i.e. the users username inside the function.

Now I'm not a fan of naming it `generateKey` as it wouldn't generate something but rather point to a unique key. I would name it `getKey` or `determineeKey` 

I hope we can figure this out quick. If there is any work needed I'm happy to help out. @ozkanonur

**Comment by ozkanonur** [comment]
> So I just need to run some stuff based on a user token.
> 
> Basically the need is. You can have multiple machines with multiple IP's but use the same account. In that case you should be able to rate limit on a unique key like a username inside a oauth2 token. Interceptors are run after guards so no real need to do something fancy but just point to i.e. the users username inside the function.
> 
> Now I'm not a fan of naming it `generateKey` as it wouldn't generate something but rather point to a unique key. I would name it `getKey` or `determineKey`
> 
> I hope we can figure this out quick. If there is any work needed I'm happy to help out. @ozkanonur

see [this](https://github.com/ozkanonur/nestjs-rate-limiter/issues/32#issuecomment-731748961)

**Comment by somehowchris** [comment]
So how I understand it #32 messes with the prefix but what it should be about right here is the actual key as having a dynamic prefix would still allow me to do an attack from multiple machines with the same identity. Or am I totally off on that?

**Pull request closed without merging**
