### PR TITLE
Adding an option to use a guard instead of an interceptor

### PR DESCRIPTION
**Pull request by JoeyEamigh**
Hey!

This is a pretty simple PR that solves [Issue #72](https://github.com/ozkanonur/nestjs-rate-limiter/issues/72).

Note: this is not heavily tested, but is verified to work.

Demo Repo: [https://github.com/JoeyEamigh/nestjs-rate-limiter-guard-demo](https://github.com/JoeyEamigh/nestjs-rate-limiter-guard-demo)

This was actually incredibly simple to do, just swapped the intercept function for a canActivate and modified the returns.

The test doesn't actually do anything because I am a real programmer and don't write tests /s (I have no clue how to use Jest)

### CODE REVIEW

**Comment by JoeyEamigh** [comment]
CodeFactor's remaining complaint is a complexity issue that exists in the interceptor as well - advise ignoring.

**Comment by ozkanonur** [comment]
> Hey!
> 
> This is a pretty simple PR that solves [Issue #72](https://github.com/ozkanonur/nestjs-rate-limiter/issues/72).
> 
> Note: this is not heavily tested, but is verified to work.
> 
> Demo Repo: https://github.com/JoeyEamigh/nestjs-rate-limiter-guard-demo
> 
> This was actually incredibly simple to do, just swapped the intercept function for a canActivate and modified the returns.
> 
> The test doesn't actually do anything because I am a real programmer and don't write tests /s (I have no clue how to use Jest)

Thank you for contributing. I will test this weekend. If it works fine without problems, then I will replace the current interceptor usage with guards.

**Comment by JoeyEamigh** [comment]
> If it works fine without problems, then I will replace the current interceptor usage with guards.

May I recommend leaving the interceptor in the codebase for backwards compatibility? I think that guards are definitely the way for new users to go but removing interceptors entirely would be a major breaking change.

Thanks for giving it a look!

**Comment by ozkanonur** [comment]
> > If it works fine without problems, then I will replace the current interceptor usage with guards.
> 
> May I recommend leaving the interceptor in the codebase for backwards compatibility? I think that guards are definitely the way for new users to go but removing interceptors entirely would be a major breaking change.
> 
> Thanks for giving it a look!

Next release version will be v3, so we can do major changes without problem and if people want to use interceptors current will be still available. Also, we will provide that information in the documentation.

**Pull request merged**
